spring:
  application:
    name: nacos-myconsumer
  cloud:
    nacos:
      discovery:
        server-addr: 123.113.182.69:8848

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true